openapi: 3.1.0
info:
  title: Charging Session Authorize Service
  description: Internal Service to support Authorize requests for initiating Charging Session
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/auth-service'
paths:
  /charging-sessions:
    post:
      tags:
        - authorize-charging-session
      summary: Authorize new Charging Session
      description: API to authorize new charging session for the given station and driver Ids
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models/auth-service.charging-session.yaml#components/schemas/ChargingSessionAuthRequest"
      responses:
        200:
          description: Charging Sessions Auth Decision
          content:
            application/json:
              schema:
                $ref: "models/auth-service.charging-session.yaml#components/schemas/ChargingSessionAuthResponse"
        default:
          description: Unknown Error
          content:
            application/json:
              schema:
                $ref: "models/common.yaml#components/schemas/ErrorResponse"
